server:
  port: 8086

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/sbp-client
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
