server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bp-transaction
    username: postgres
    password: Password123!

  jpa:
    hibernate:
      ddl-auto: update
