server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bp-client
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
