server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/sbp-transaction
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
